import ProjectDescription

let config = Config(
    compatibleXcodeVersions: .all,
    generationOptions: .options(
        enforceExplicitDependencies: false,
        disableAutogeneratedSchemes: false,
        resolveDependenciesWithSystemScm: true
    ),
    swiftVersion: "5.9"
)
